title: Credo Map
description: 撮影チーム専用\n「Credo Map」
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRE5ubWwkh97plT8zYTFryeNef-kuPail3UsYPn9F35ZG749lc08fomNKnA7QlLoJvJH3XnvQWJWRAo/pub?gid=1957425126&single=true&output=csv
form_url:
logo_image_url: https://geoloniamaps.github.io/pwamap/icon-pwamap.svg
background_image_url: https://geoloniamaps.github.io/pwamap/geolonia_bgimage_1920_1080.png
primary_color: "#d2691e"
orderby: distance
